<a href="https://colab.research.google.com/github/bryanpioloEspanol/bryan-espanol/blob/main/Matrix_and_its_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#Create a 2x4 array 
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a)
print(b)



[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [2]:
#Sum of a+b
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [3]:
#diffirence1 = a-b
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [4]:
#diffirence1 = a-b
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]
